--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SoyDavs/DiscordAuth
build-by-default: true
branches:
- main
projects:
  DiscordAuth:
    path: ""
    lint:
      phpstan: false 
...
